language: node_js
node_js:
  - "0.12.16"
  - "4.0.0"
  - "5.0.0"
  - "6.0.0"
  - "6.5.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
