language: node_js
node_js:
  - "4.6.0"
  - "5.12.0"
  - "6.8.1"
before_install:
  - npm i -g yarn
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - yarn
  - cd js-given
  - yarn
  - npm run postinstall
  - cd ../documentation
  - yarn
  - cd ..
