language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - js-given/node_modules
    - documentation/node_modules
    - examples/jest-es2015/node_modules
node_js:
  - "4.8.3"
  - "6.10.3"
  - "7.10.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - yarn
